README.org --- description



Copyright (C) 2020 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>



  This file is part of optical-flow.

  optical-flow is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  optical-flow is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with optical-flow.  If not, see <http://www.gnu.org/licenses/>.



* Keywords:
optical flow block matching

* Description:

* Usage:
Generate image with random texture
mx=1920;my=1080;head -c "$((3*mx*my))" /dev/urandom | display -depth 8 -size "${mx}x${my}" RGB:-
Or scaled
mx=100;my=100;head -c "$((3*mx*my))" /dev/urandom | display -depth 8 -size "${mx}x${my}" -filter box -resize 1000x1000 RGB:-
Or grey
mx=100;my=100;head -c "$((3*mx*my))" /dev/urandom | display -depth 8 -size "${mx}x${my}" -filter box -resize 1000x1000 -colorspace gray RGB:-
Or black/white
mx=100;my=50;head -c "$((3*mx*my))" /dev/urandom | display -depth 8 -size "${mx}x${my}" -filter box -resize 2000x1000 -colorspace gray -threshold 50% RGB:-
Or save it as PNG, and view with image viewer on you screen
mx=320;my=256;head -c "$((3*mx*my))" /dev/urandom | convert -depth 8 -size "${mx}x${my}" RGB:- random.png

Use the webcam to view the image of the texture on the monitor screen
(or print the texture), and place an optically inhomogeneous object
between the webcam and the texture:
./optical_flow -v 2 -d /dev/video0
Or
./optical_flow -v 2 -d 'rtsp://user:password@192.168.100.101/Streaming/channels/101'
Or if you have many stored video files
find ../../../media/optical-flow -type f -regextype egrep -iregex '.*((avi|mpeg|mpg|mp4|webm|mkv))' -print0 | xargs -0 --max-args=1 ./optical_flow -v 2 -d


press space for show only optical flow
* History:
Project created at 2022-04(Apr)-12

* Dependences:
